services:
  db:
    image: postgres:15-alpine
    container_name: anime_db
    environment:
      POSTGRES_DB: clicker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d clicker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/demo
    container_name: anime_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clicker_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: anime_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend